#!/bin/bash

# ===================================================
# Script: find_dcs.sh
# Descrição: Lista os Controladores de Domínio (DCs) do Active Directory (AD)
# Data: 03 de Outubro de 2025
# Generated by: Google Gemini (para análise e documentação)
# ===================================================

# Define o banner
BANNER=$(cat << "EOF"
----------------------------------------------------
| AD DC Finder v1.0 |
----------------------------------------------------
| Descrição: Consulta o DNS para listar os |
| Controladores de Domínio (DCs) de um AD. |
----------------------------------------------------
EOF
)

# Verifica se um domínio foi informado
if [ -z "$1" ]; then
    echo "$BANNER"
    echo
    echo "⚠️ ERRO: Domínio não informado!"
    echo "Uso: $0 dominio.com"
    echo
    exit 1
fi

DOMAIN="$1"

# Obtém os registros SRV dos Domain Controllers
# O registro SRV padrão do AD é: _ldap._tcp.dc._msdcs.<dominio>
SRV_RECORDS=$(dig +short _ldap._tcp.dc._msdcs."$DOMAIN" SRV)

# Verifica se encontrou algum resultado
if [ -z "$SRV_RECORDS" ]; then
    echo "❌ Nenhum controlador de domínio encontrado para o domínio: $DOMAIN"
    echo "Verifique se o domínio está correto ou se o servidor DNS responde por ele."
    exit 2
fi

# Extrai apenas os nomes dos DCs (última coluna de cada linha)
# 1. awk '{print $NF}' pega o hostname (última coluna da saída do dig)
# 2. sed 's/\.$//' remove o ponto final (trailing dot) do hostname
DC_LIST=$(echo "$SRV_RECORDS" | awk '{print $NF}' | sed 's/\.$//')

# Apresenta o resultado
echo
echo "✅ Controladores de Domínio encontrados para o AD: $DOMAIN"
echo "============================================="

COUNT=1
while read -r DC; do
    # printf "%02d" $COUNT formata o número com zero à esquerda (ex: 01, 02)
    echo "- $(printf "%02d" $COUNT) - $DC"
    ((COUNT++))
done <<< "$DC_LIST"

echo
